package com.hcsc.provider.attestation.drools.drl
 
import com.hcsc.provider.attestation.model.Provider;
import com.hcsc.provider.attestation.model.Validation;

rule "Initial Rule"
    dialect "mvel"
  when
   $provider: Provider(status == null)
  then
  	System.out.println("This provider null is CORRECT");
    $provider.setStatus(Validation.UNKNOWN);
end

rule "Valid provider"
  dialect "mvel"
  when
   $provider : Provider( taxId.length() != 11, npi.length() != 10)
  then
   System.out.println("This Valid provide is FAILED");
   $provider.setStatus(Validation.FAILED);
end
rule "prov-speciality code"
    dialect "mvel"
  when
   $provider: Provider(providerSpecialityCode != "C5")
  then
   System.out.println("This prov-speciality code is FAILED");
    $provider.setStatus(Validation.FAILED);
end

rule "Final Rule"
    dialect "mvel"
  when
   $provider: Provider(status == Validation.UNKNOWN)
  then
  System.out.println("This Validation.UNKNOWN is FAILED");
    $provider.setStatus(Validation.PASSED);
end

